name: checks
on: [push, pull_request]
jobs:
  checks:
    strategy:
      matrix:
        php: ['7.4']
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: composer,phive
      - name: Install CMSimple_XH
        run: |
          curl -fsSL -o CMSimple_XH-1.7.5.zip https://github.com/cmsimple-xh/cmsimple-xh/releases/download/1.7.5/CMSimple_XH-1.7.5.zip
          unzip -q CMSimple_XH-1.7.5.zip
      - name: Checkout Plib_XH
        uses: actions/checkout@v2
        with:
          path: cmsimplexh/plugins/plib
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: cmsimplexh/plugins/plib/tools
          key: tools-${{hashFiles('cmsimplexh/plugins/plib/.phive')}}
      - if: ${{steps.cache-tools.outputs.cache-hit != 'true'}}
        name: phive install
        run: cd cmsimplexh/plugins/plib && phive --no-progress install --trust-gpg-keys 0F9684B8B16B7AB0,31C7E470E2138192,51C67305FFC2E5C0,9093F8B32E4815AA,A978220305CD5C32,CF1A108D0E7AE720,D5F0CB76E2DD74F8
      - name: composer install
        run: cd cmsimplexh/plugins/plib && composer install
      - name: phing sniff
        run: cd cmsimplexh/plugins/plib && PATH=tools:vendor/bin:$PATH phing sniff
      - name: phing stan
        run: cd cmsimplexh/plugins/plib && PATH=tools:vendor/bin:$PATH phing stan
      - name: phing mess
        run: cd cmsimplexh/plugins/plib && PATH=tools:vendor/bin:$PATH phing mess
      - name: phing unit-tests
        run: cd cmsimplexh/plugins/plib && PATH=tools:vendor/bin:$PATH phing unit-tests
